### ISSUE TITLE
Feature request: list of pages that contain highlights

### ISSUE THREAD

**Issue by idiosyn** [jeromepl/highlighter#38] opened 2022-07-29 03:04 UTC
Hello, thanks for this great extension.

One feature I’d love to see is a list of pages that contain highlights.

It would be useful to know in which pages I have highlighted text.

I often highlight text on a page for a quick task, close the tab and forget about it. Over time I’d end up with hundreds of pages with highlighted text, but no easy way to access them. (I primarily would access them to delete all their highlights, but I imagine many users would benefit from accessing them to check something up.)

**Comment by jeromepl** [comment] 2022-07-29 12:49
Hi! Thanks for the feedback, this is indeed a long-awaited feature that would be a great addition to this tool.
I'm going to close this issue as it is a duplicate of #6 . I invite to track its progress over there 🙂

**Closed by jeromepl** 2022-07-29 12:49 UTC
